# Generated by Django 4.2.6 on 2024-06-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menutype_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='descd',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
