# Generated by Django 4.2.6 on 2024-06-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menutype_persons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menutype',
            old_name='materials',
            new_name='materialsgram',
        ),
        migrations.AddField(
            model_name='menutype',
            name='materialsgram1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menutype',
            name='materialsgram2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
