# Generated by Django 4.2.6 on 2024-06-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_rename_materials_menutype_materialsgram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menutype',
            name='materialsname1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menutype',
            name='materialsname2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
