# Generated by Django 4.2.6 on 2024-06-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menutype_img1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menutype',
            old_name='img1',
            new_name='logoimg',
        ),
    ]
