# Generated by Django 4.2.6 on 2024-06-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_rename_img1_menutype_logoimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menutype',
            old_name='logoimg',
            new_name='logo_img',
        ),
    ]
