# Generated by Django 4.2.6 on 2024-06-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_rename_logoimg_menutype_logo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menutype',
            name='logo_img',
        ),
    ]
